import os
import requests

urls = [
  "https://www.amcharts.com/lib/3/maps/svg/afghanistanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/africaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/albaniaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/algeriaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/americanSamoaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/andorraLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/angolaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/anguillaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/antiguaBarbudaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/argentinaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/armeniaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/arubaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/asiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/australiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/austriaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/azerbaijanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/bahamasLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/bahrainLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/bangladeshLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/barbadosLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/belarusLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/belgiumLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/belizeLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/beninLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/bermudaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/bhutanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/boliviaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/bosniaHerzegovinaCantonsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/bosniaHerzegovinaRegionsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/botswanaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/brazilLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/britishVirginIslandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/bruneiDarussalamLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/bulgariaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/burkinaFasoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/burundiLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/cambodiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/cameroonLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/canadaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/capeVerdeLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/caribbeanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/caribbeanNetherlandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/caymanIslandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/centralAfricanRepublicLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/centralAmericaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/chadLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/channelIslandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/chileLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/chinaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/christmasIslandLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/cocosIslandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/colombiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/comorosLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/congoDRLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/congoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/continents2Low.svg",
  "https://www.amcharts.com/lib/3/maps/svg/continentsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/continentsRegionsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/continentsWithAntarcticaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/cookIslandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/costaRicaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/croatiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/cubaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/curacaoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/cyprusLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/cyprusNorthernCyprusLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/czechRepublicLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/denmarkLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/djiboutiLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/dominicaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/dominicanRepublicLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/eSwatiniLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/eastTimorLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/ecuadorLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/egyptLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/elSalvadorLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/equatorialGuineaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/eritreaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/estoniaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/ethiopiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/europeLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/falklandIslandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/faroeIslandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/fijiEastLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/fijiWestLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/finlandLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/france2016Low.svg",
  "https://www.amcharts.com/lib/3/maps/svg/franceDepartmentsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/franceLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/frenchGuianaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/frenchPolynesiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/gabonLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/gambiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/georgiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/georgiaSouthOssetiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/germanyLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/ghanaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/gibraltarLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/greeceLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/greenlandLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/grenadaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/guadeloupeLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/guamLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/guatemalaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/guineaBissauLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/guineaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/guyanaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/haitiLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/hondurasLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/hongKongLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/hungaryLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/icelandLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/india2019Low.svg",
  "https://www.amcharts.com/lib/3/maps/svg/indiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/indonesiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/iranLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/iraqLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/irelandLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/isleOfManLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/israelLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/israelPalestineLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/italyLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/ivoryCoastLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/jamaicaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/japanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/jerseyLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/jordanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/kazakhstanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/kenyaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/kiribatiLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/kosovoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/kuwaitLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/kyrgyzstanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/laosLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/latinAmericaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/latviaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/lebanonLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/lesothoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/liberiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/libyaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/liechtensteinLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/lithuaniaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/luxembourgLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/macaoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/macedoniaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/madagascarLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/malawiLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/malaysiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/maldivesLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/maliLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/maltaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/marshallIslandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/martiniqueLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/mauritaniaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/mauritiusLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/mayotteLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/mexicoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/micronesiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/middleEastLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/moldovaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/monacoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/mongoliaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/montenegroLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/montserratLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/morocco2015Low.svg",
  "https://www.amcharts.com/lib/3/maps/svg/moroccoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/moroccoWesternSaharaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/mozambiqueLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/myanmarLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/namibiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/nauruLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/nepalLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/netherlandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/newCaledoniaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/newZealandLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/nicaraguaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/nigerLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/nigeriaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/niueLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/northKoreaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/norwayLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/oceaniaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/omanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/pakistanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/palauLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/palestineLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/panamaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/papuaNewGuineaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/paraguayLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/peruLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/philippinesLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/pitcairnIslandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/polandLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/portugalLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/portugalRegionsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/puertoRicoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/qatarLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/reunionLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/romaniaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/russiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/rwandaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/saintMartinLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/saintPierreMiquelonLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/samoaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/sanMarinoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/saoTomePrincipeLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/saudiArabiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/senegalLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/serbiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/serbiaNoKosovoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/seychellesLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/sierraLeoneLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/singaporeLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/sintMaartenLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/slovakiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/sloveniaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/solomonIslandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/somaliaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/southAfricaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/southAmericaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/southKoreaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/southSudanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/spainLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/spainProvincesLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/sriLankaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/stHelenaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/stKittsNevisLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/stLuciaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/stVincentLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/sudanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/surinameLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/svalbardJanMayenLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/swedenLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/switzerlandLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/syriaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/taiwanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/tajikistanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/tanzaniaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/thailandLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/tibetLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/togoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/tokelauLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/tongaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/trinidadAndTobagoLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/tunisiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/turkeyLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/turkmenistanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/turksCaicosIslandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/tuvaluLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/ugandaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/ukCountiesLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/ukraineLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/unRegionsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/unitedArabEmiratesLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/unitedKingdomLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/uruguayLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/usVirginIslandsLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/usa2Low.svg",
  "https://www.amcharts.com/lib/3/maps/svg/usaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/usaMercatorLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/usaTerritories2Low.svg",
  "https://www.amcharts.com/lib/3/maps/svg/usaTerritoriesLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/uzbekistanLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/vanuatuLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/vaticanCityLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/venezuelaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/vietnamLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/wallisFutunaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/yemenLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/zambiaLow.svg",
  "https://www.amcharts.com/lib/3/maps/svg/zimbabwLow.svge"
]

countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burma",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo, Democratic Republic of",
    "Congo, Republic of the",
    "Cook Islands",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Curacao",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands(Islas Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Polynesia",
    "Gabon",
    "Gambia",
    "Gaza Strip",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "NorthKorea",
    "SouthKorea",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia, Federated States of",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Helena, Ascension, and Tristan da Cunha",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey(Turkiye)",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Virgin Islands",
    "Wallis and Futuna",
    "West Bank",
    "Yemen",
    "Zambia",
    "Zimbabwe"
]

# Normalize both lists of countries to lowercase
normalized_urls = [url.split("/")[-1].split("Low")[0].lower() for url in urls]
normalized_countries = [country.lower() for country in countries]

# Directory to save SVG images
directory = "country_outlines"
if not os.path.exists(directory):
  os.makedirs(directory)

# List to store countries that didn't get downloaded
not_downloaded_countries = []

# Function to download and save SVG image from URL


def download_svg(url):
  filename = url.split("/")[-1]  # Extract filename from URL
  filename = filename.replace("Low", "")
  filepath = os.path.join(directory, filename)
  response = requests.get(url)
  if response.status_code == 200:
    with open(filepath, 'wb') as f:
      f.write(response.content)
      print(f"Downloaded {filename}")
  else:
    print(f"Failed to download {filename}")
    # Add country to not_downloaded_countries list
    not_downloaded_countries.append(filename.split("Low")[0])


# Download SVG images from each URL if the country exists in the list of countries
for url in urls:
  # Extract country name from URL
  country_name = url.split("/")[-1].split("Low")[0]
  normalized_country = country_name.lower()  # Normalize country name
  if normalized_country in normalized_countries:
    download_svg(url)

# Print countries that didn't get downloaded
print("Countries that didn't get downloaded:")
for country in not_downloaded_countries:
  print(country)
