import os
import requests

urls = [
  "https://www.amcharts.com/svg-maps/?map=afghanistan",
  "https://www.amcharts.com/svg-maps/?map=africa",
  "https://www.amcharts.com/svg-maps/?map=albania",
  "https://www.amcharts.com/svg-maps/?map=algeria",
  "https://www.amcharts.com/svg-maps/?map=americanSamoa",
  "https://www.amcharts.com/svg-maps/?map=andorra",
  "https://www.amcharts.com/svg-maps/?map=angola",
  "https://www.amcharts.com/svg-maps/?map=anguilla",
  "https://www.amcharts.com/svg-maps/?map=antiguaBarbuda",
  "https://www.amcharts.com/svg-maps/?map=argentina",
  "https://www.amcharts.com/svg-maps/?map=armenia",
  "https://www.amcharts.com/svg-maps/?map=aruba",
  "https://www.amcharts.com/svg-maps/?map=asia",
  "https://www.amcharts.com/svg-maps/?map=australia",
  "https://www.amcharts.com/svg-maps/?map=austria",
  "https://www.amcharts.com/svg-maps/?map=azerbaijan",
  "https://www.amcharts.com/svg-maps/?map=bahamas",
  "https://www.amcharts.com/svg-maps/?map=bahrain",
  "https://www.amcharts.com/svg-maps/?map=bangladesh",
  "https://www.amcharts.com/svg-maps/?map=barbados",
  "https://www.amcharts.com/svg-maps/?map=belarus",
  "https://www.amcharts.com/svg-maps/?map=belgium",
  "https://www.amcharts.com/svg-maps/?map=belize",
  "https://www.amcharts.com/svg-maps/?map=benin",
  "https://www.amcharts.com/svg-maps/?map=bermuda",
  "https://www.amcharts.com/svg-maps/?map=bhutan",
  "https://www.amcharts.com/svg-maps/?map=bolivia",
  "https://www.amcharts.com/svg-maps/?map=bosniaHerzegovinaCantons",
  "https://www.amcharts.com/svg-maps/?map=bosniaHerzegovinaRegions",
  "https://www.amcharts.com/svg-maps/?map=botswana",
  "https://www.amcharts.com/svg-maps/?map=brazil",
  "https://www.amcharts.com/svg-maps/?map=britishVirginIslands",
  "https://www.amcharts.com/svg-maps/?map=bruneiDarussalam",
  "https://www.amcharts.com/svg-maps/?map=bulgaria",
  "https://www.amcharts.com/svg-maps/?map=burkinaFaso",
  "https://www.amcharts.com/svg-maps/?map=burundi",
  "https://www.amcharts.com/svg-maps/?map=cambodia",
  "https://www.amcharts.com/svg-maps/?map=cameroon",
  "https://www.amcharts.com/svg-maps/?map=canada",
  "https://www.amcharts.com/svg-maps/?map=capeVerde",
  "https://www.amcharts.com/svg-maps/?map=caribbean",
  "https://www.amcharts.com/svg-maps/?map=caribbeanNetherlands",
  "https://www.amcharts.com/svg-maps/?map=caymanIslands",
  "https://www.amcharts.com/svg-maps/?map=centralAfricanRepublic",
  "https://www.amcharts.com/svg-maps/?map=centralAmerica",
  "https://www.amcharts.com/svg-maps/?map=chad",
  "https://www.amcharts.com/svg-maps/?map=channelIslands",
  "https://www.amcharts.com/svg-maps/?map=chile",
  "https://www.amcharts.com/svg-maps/?map=china",
  "https://www.amcharts.com/svg-maps/?map=christmasIsland",
  "https://www.amcharts.com/svg-maps/?map=cocosIslands",
  "https://www.amcharts.com/svg-maps/?map=colombia",
  "https://www.amcharts.com/svg-maps/?map=comoros",
  "https://www.amcharts.com/svg-maps/?map=congoDR",
  "https://www.amcharts.com/svg-maps/?map=congo",
  "https://www.amcharts.com/svg-maps/?map=continents2",
  "https://www.amcharts.com/svg-maps/?map=continents",
  "https://www.amcharts.com/svg-maps/?map=continentsRegions",
  "https://www.amcharts.com/svg-maps/?map=continentsWithAntarctica",
  "https://www.amcharts.com/svg-maps/?map=cookIslands",
  "https://www.amcharts.com/svg-maps/?map=costaRica",
  "https://www.amcharts.com/svg-maps/?map=croatia",
  "https://www.amcharts.com/svg-maps/?map=cuba",
  "https://www.amcharts.com/svg-maps/?map=curacao",
  "https://www.amcharts.com/svg-maps/?map=cyprus",
  "https://www.amcharts.com/svg-maps/?map=cyprusNorthernCyprus",
  "https://www.amcharts.com/svg-maps/?map=czechRepublic",
  "https://www.amcharts.com/svg-maps/?map=denmark",
  "https://www.amcharts.com/svg-maps/?map=djibouti",
  "https://www.amcharts.com/svg-maps/?map=dominica",
  "https://www.amcharts.com/svg-maps/?map=dominicanRepublic",
  "https://www.amcharts.com/svg-maps/?map=eSwatini",
  "https://www.amcharts.com/svg-maps/?map=eastTimor",
  "https://www.amcharts.com/svg-maps/?map=ecuador",
  "https://www.amcharts.com/svg-maps/?map=egypt",
  "https://www.amcharts.com/svg-maps/?map=elSalvador",
  "https://www.amcharts.com/svg-maps/?map=equatorialGuinea",
  "https://www.amcharts.com/svg-maps/?map=eritrea",
  "https://www.amcharts.com/svg-maps/?map=estonia",
  "https://www.amcharts.com/svg-maps/?map=ethiopia",
  "https://www.amcharts.com/svg-maps/?map=europe",
  "https://www.amcharts.com/svg-maps/?map=falklandIslands",
  "https://www.amcharts.com/svg-maps/?map=faroeIslands",
  "https://www.amcharts.com/svg-maps/?map=fijiEast",
  "https://www.amcharts.com/svg-maps/?map=fijiWest",
  "https://www.amcharts.com/svg-maps/?map=finland",
  "https://www.amcharts.com/svg-maps/?map=france2016",
  "https://www.amcharts.com/svg-maps/?map=franceDepartments",
  "https://www.amcharts.com/svg-maps/?map=france",
  "https://www.amcharts.com/svg-maps/?map=frenchGuiana",
  "https://www.amcharts.com/svg-maps/?map=frenchPolynesia",
  "https://www.amcharts.com/svg-maps/?map=gabon",
  "https://www.amcharts.com/svg-maps/?map=gambia",
  "https://www.amcharts.com/svg-maps/?map=georgia",
  "https://www.amcharts.com/svg-maps/?map=georgiaSouthOssetia",
  "https://www.amcharts.com/svg-maps/?map=germany",
  "https://www.amcharts.com/svg-maps/?map=ghana",
  "https://www.amcharts.com/svg-maps/?map=gibraltar",
  "https://www.amcharts.com/svg-maps/?map=greece",
  "https://www.amcharts.com/svg-maps/?map=greenland",
  "https://www.amcharts.com/svg-maps/?map=grenada",
  "https://www.amcharts.com/svg-maps/?map=guadeloupe",
  "https://www.amcharts.com/svg-maps/?map=guam",
  "https://www.amcharts.com/svg-maps/?map=guatemala",
  "https://www.amcharts.com/svg-maps/?map=guineaBissau",
  "https://www.amcharts.com/svg-maps/?map=guinea",
  "https://www.amcharts.com/svg-maps/?map=guyana",
  "https://www.amcharts.com/svg-maps/?map=haiti",
  "https://www.amcharts.com/svg-maps/?map=honduras",
  "https://www.amcharts.com/svg-maps/?map=hongKong",
  "https://www.amcharts.com/svg-maps/?map=hungary",
  "https://www.amcharts.com/svg-maps/?map=iceland",
  "https://www.amcharts.com/svg-maps/?map=india2019",
  "https://www.amcharts.com/svg-maps/?map=india",
  "https://www.amcharts.com/svg-maps/?map=indonesia",
  "https://www.amcharts.com/svg-maps/?map=iran",
  "https://www.amcharts.com/svg-maps/?map=iraq",
  "https://www.amcharts.com/svg-maps/?map=ireland",
  "https://www.amcharts.com/svg-maps/?map=isleOfMan",
  "https://www.amcharts.com/svg-maps/?map=israel",
  "https://www.amcharts.com/svg-maps/?map=israelPalestine",
  "https://www.amcharts.com/svg-maps/?map=italy",
  "https://www.amcharts.com/svg-maps/?map=ivoryCoast",
  "https://www.amcharts.com/svg-maps/?map=jamaica",
  "https://www.amcharts.com/svg-maps/?map=japan",
  "https://www.amcharts.com/svg-maps/?map=jersey",
  "https://www.amcharts.com/svg-maps/?map=jordan",
  "https://www.amcharts.com/svg-maps/?map=kazakhstan",
  "https://www.amcharts.com/svg-maps/?map=kenya",
  "https://www.amcharts.com/svg-maps/?map=kiribati",
  "https://www.amcharts.com/svg-maps/?map=kosovo",
  "https://www.amcharts.com/svg-maps/?map=kuwait",
  "https://www.amcharts.com/svg-maps/?map=kyrgyzstan",
  "https://www.amcharts.com/svg-maps/?map=laos",
  "https://www.amcharts.com/svg-maps/?map=latinAmerica",
  "https://www.amcharts.com/svg-maps/?map=latvia",
  "https://www.amcharts.com/svg-maps/?map=lebanon",
  "https://www.amcharts.com/svg-maps/?map=lesotho",
  "https://www.amcharts.com/svg-maps/?map=liberia",
  "https://www.amcharts.com/svg-maps/?map=libya",
  "https://www.amcharts.com/svg-maps/?map=liechtenstein",
  "https://www.amcharts.com/svg-maps/?map=lithuania",
  "https://www.amcharts.com/svg-maps/?map=luxembourg",
  "https://www.amcharts.com/svg-maps/?map=macao",
  "https://www.amcharts.com/svg-maps/?map=macedonia",
  "https://www.amcharts.com/svg-maps/?map=madagascar",
  "https://www.amcharts.com/svg-maps/?map=malawi",
  "https://www.amcharts.com/svg-maps/?map=malaysia",
  "https://www.amcharts.com/svg-maps/?map=maldives",
  "https://www.amcharts.com/svg-maps/?map=mali",
  "https://www.amcharts.com/svg-maps/?map=malta",
  "https://www.amcharts.com/svg-maps/?map=marshallIslands",
  "https://www.amcharts.com/svg-maps/?map=martinique",
  "https://www.amcharts.com/svg-maps/?map=mauritania",
  "https://www.amcharts.com/svg-maps/?map=mauritius",
  "https://www.amcharts.com/svg-maps/?map=mayotte",
  "https://www.amcharts.com/svg-maps/?map=mexico",
  "https://www.amcharts.com/svg-maps/?map=micronesia",
  "https://www.amcharts.com/svg-maps/?map=middleEast",
  "https://www.amcharts.com/svg-maps/?map=moldova",
  "https://www.amcharts.com/svg-maps/?map=monaco",
  "https://www.amcharts.com/svg-maps/?map=mongolia",
  "https://www.amcharts.com/svg-maps/?map=montenegro",
  "https://www.amcharts.com/svg-maps/?map=montserrat",
  "https://www.amcharts.com/svg-maps/?map=morocco2015",
  "https://www.amcharts.com/svg-maps/?map=morocco",
  "https://www.amcharts.com/svg-maps/?map=moroccoWesternSahara",
  "https://www.amcharts.com/svg-maps/?map=mozambique",
  "https://www.amcharts.com/svg-maps/?map=myanmar",
  "https://www.amcharts.com/svg-maps/?map=namibia",
  "https://www.amcharts.com/svg-maps/?map=nauru",
  "https://www.amcharts.com/svg-maps/?map=nepal",
  "https://www.amcharts.com/svg-maps/?map=netherlands",
  "https://www.amcharts.com/svg-maps/?map=newCaledonia",
  "https://www.amcharts.com/svg-maps/?map=newZealand",
  "https://www.amcharts.com/svg-maps/?map=nicaragua",
  "https://www.amcharts.com/svg-maps/?map=niger",
  "https://www.amcharts.com/svg-maps/?map=nigeria",
  "https://www.amcharts.com/svg-maps/?map=niue",
  "https://www.amcharts.com/svg-maps/?map=northKorea",
  "https://www.amcharts.com/svg-maps/?map=norway",
  "https://www.amcharts.com/svg-maps/?map=oceania",
  "https://www.amcharts.com/svg-maps/?map=oman",
  "https://www.amcharts.com/svg-maps/?map=pakistan",
  "https://www.amcharts.com/svg-maps/?map=palau",
  "https://www.amcharts.com/svg-maps/?map=palestine",
  "https://www.amcharts.com/svg-maps/?map=panama",
  "https://www.amcharts.com/svg-maps/?map=papuaNewGuinea",
  "https://www.amcharts.com/svg-maps/?map=paraguay",
  "https://www.amcharts.com/svg-maps/?map=peru",
  "https://www.amcharts.com/svg-maps/?map=philippines",
  "https://www.amcharts.com/svg-maps/?map=pitcairnIslands",
  "https://www.amcharts.com/svg-maps/?map=poland",
  "https://www.amcharts.com/svg-maps/?map=portugal",
  "https://www.amcharts.com/svg-maps/?map=portugalRegions",
  "https://www.amcharts.com/svg-maps/?map=puertoRico",
  "https://www.amcharts.com/svg-maps/?map=qatar",
  "https://www.amcharts.com/svg-maps/?map=reunion",
  "https://www.amcharts.com/svg-maps/?map=romania",
  "https://www.amcharts.com/svg-maps/?map=russia",
  "https://www.amcharts.com/svg-maps/?map=rwanda",
  "https://www.amcharts.com/svg-maps/?map=saintMartin",
  "https://www.amcharts.com/svg-maps/?map=saintPierreMiquelon",
  "https://www.amcharts.com/svg-maps/?map=samoa",
  "https://www.amcharts.com/svg-maps/?map=sanMarino",
  "https://www.amcharts.com/svg-maps/?map=saoTomePrincipe",
  "https://www.amcharts.com/svg-maps/?map=saudiArabia",
  "https://www.amcharts.com/svg-maps/?map=senegal",
  "https://www.amcharts.com/svg-maps/?map=serbia",
  "https://www.amcharts.com/svg-maps/?map=serbiaNoKosovo",
  "https://www.amcharts.com/svg-maps/?map=seychelles",
  "https://www.amcharts.com/svg-maps/?map=sierraLeone",
  "https://www.amcharts.com/svg-maps/?map=singapore",
  "https://www.amcharts.com/svg-maps/?map=sintMaarten",
  "https://www.amcharts.com/svg-maps/?map=slovakia",
  "https://www.amcharts.com/svg-maps/?map=slovenia",
  "https://www.amcharts.com/svg-maps/?map=solomonIslands",
  "https://www.amcharts.com/svg-maps/?map=somalia",
  "https://www.amcharts.com/svg-maps/?map=southAfrica",
  "https://www.amcharts.com/svg-maps/?map=southAmerica",
  "https://www.amcharts.com/svg-maps/?map=southKorea",
  "https://www.amcharts.com/svg-maps/?map=southSudan",
  "https://www.amcharts.com/svg-maps/?map=spain",
  "https://www.amcharts.com/svg-maps/?map=spainProvinces",
  "https://www.amcharts.com/svg-maps/?map=sriLanka",
  "https://www.amcharts.com/svg-maps/?map=stHelena",
  "https://www.amcharts.com/svg-maps/?map=stKittsNevis",
  "https://www.amcharts.com/svg-maps/?map=stLucia",
  "https://www.amcharts.com/svg-maps/?map=stVincent",
  "https://www.amcharts.com/svg-maps/?map=sudan",
  "https://www.amcharts.com/svg-maps/?map=suriname",
  "https://www.amcharts.com/svg-maps/?map=svalbardJanMayen",
  "https://www.amcharts.com/svg-maps/?map=sweden",
  "https://www.amcharts.com/svg-maps/?map=switzerland",
  "https://www.amcharts.com/svg-maps/?map=syria",
  "https://www.amcharts.com/svg-maps/?map=taiwan",
  "https://www.amcharts.com/svg-maps/?map=tajikistan",
  "https://www.amcharts.com/svg-maps/?map=tanzania",
  "https://www.amcharts.com/svg-maps/?map=thailand",
  "https://www.amcharts.com/svg-maps/?map=tibet",
  "https://www.amcharts.com/svg-maps/?map=togo",
  "https://www.amcharts.com/svg-maps/?map=tokelau",
  "https://www.amcharts.com/svg-maps/?map=tonga",
  "https://www.amcharts.com/svg-maps/?map=trinidadAndTobago",
  "https://www.amcharts.com/svg-maps/?map=tunisia",
  "https://www.amcharts.com/svg-maps/?map=turkey",
  "https://www.amcharts.com/svg-maps/?map=turkmenistan",
  "https://www.amcharts.com/svg-maps/?map=turksCaicosIslands",
  "https://www.amcharts.com/svg-maps/?map=tuvalu",
  "https://www.amcharts.com/svg-maps/?map=uganda",
  "https://www.amcharts.com/svg-maps/?map=ukCounties",
  "https://www.amcharts.com/svg-maps/?map=ukraine",
  "https://www.amcharts.com/svg-maps/?map=unRegions",
  "https://www.amcharts.com/svg-maps/?map=unitedArabEmirates",
  "https://www.amcharts.com/svg-maps/?map=unitedKingdom",
  "https://www.amcharts.com/svg-maps/?map=uruguay",
  "https://www.amcharts.com/svg-maps/?map=usVirginIslands",
  "https://www.amcharts.com/svg-maps/?map=usa2",
  "https://www.amcharts.com/svg-maps/?map=usa",
  "https://www.amcharts.com/svg-maps/?map=usaMercator",
  "https://www.amcharts.com/svg-maps/?map=usaTerritories2",
  "https://www.amcharts.com/svg-maps/?map=usaTerritories",
  "https://www.amcharts.com/svg-maps/?map=uzbekistan",
  "https://www.amcharts.com/svg-maps/?map=vanuatu",
  "https://www.amcharts.com/svg-maps/?map=vaticanCity",
  "https://www.amcharts.com/svg-maps/?map=venezuela",
  "https://www.amcharts.com/svg-maps/?map=vietnam",
  "https://www.amcharts.com/svg-maps/?map=wallisFutuna",
  "https://www.amcharts.com/svg-maps/?map=yemen",
  "https://www.amcharts.com/svg-maps/?map=zambia",
  "https://www.amcharts.com/svg-maps/?map=zimbabwe"
]

countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burma",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo, Democratic Republic of",
    "Congo, Republic of the",
    "Cook Islands",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Curacao",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands(Islas Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Polynesia",
    "Gabon",
    "Gambia",
    "Gaza Strip",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "NorthKorea",
    "SouthKorea",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia, Federated States of",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Helena, Ascension, and Tristan da Cunha",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey(Turkiye)",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Virgin Islands",
    "Wallis and Futuna",
    "West Bank",
    "Yemen",
    "Zambia",
    "Zimbabwe"
]

normalized_urls = [url.split("=")[-1].lower() for url in urls]
normalized_countries = [country.lower() for country in countries]

directory = "country_outlines"
if not os.path.exists(directory):
  os.makedirs(directory)

not_downloaded_countries = []

def download_svg(url):
  filename = url.split("=")[-1] + ".svg"
  filepath = os.path.join(directory, filename)
  response = requests.get(url)
  if response.status_code == 200:
    with open(filepath, 'wb') as f:
      f.write(response.content)
      print(f"Downloaded {filename}")
  else:
    print(f"Failed to download {filename}")
    not_downloaded_countries.append(url.split("=")[-1])

for url in urls:
  country_name = url.split("=")[-1]
  normalized_country = country_name.lower()
  if normalized_country in normalized_countries:
    download_svg(url)

print("Countries that didn't get downloaded:")
for country in not_downloaded_countries:
  print(country)
