export type CountryData = {
  [key: string]: string;
  official_country_name: string;
  total_area: string;
  land_area: string;
  water_area: string;
  boundaries_distance: string;
  random_border_country: string;
  highest_elevation: string;
  mean_elevation: string;
  coastline_distance: string;
  landlocked: string;
  latitude: string;
  longitude: string;
  population: string;
  most_popular_religion: string;
  median_age: string;
  population_growth_rate: string;
  birth_rate: string;
  death_rate: string;
  sex_ratio: string;
  infant_mortality_rate: string;
  life_expectancy_at_birth: string;
  drinking_water_access_pct: string;
  obesity: string;
  literacy: string;
  government_type: string;
  GDP: string;
  GDP_growth_rate: string;
  GDP_per_capita: string;
  labor_force: string;
  unemployment_rate: string;
  population_below_poverty_line: string;
  total_exports: string;
  export_partners: string;
  export_commodities: string;
  total_imports: string;
  import_partners: string;
  electricity_access: string;
  mobile_phone_subscriptions: string;
  internet_users_total: string;
  internet_users_pct: string;
  internet_country_code: string;
};

export type CountriesData = {
  [key: string]: CountryData;
};
